/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Jobs.java
 *
 * Created on 27-Jul-2010, 14:05:05
 */

package phoniex.GUI;

import phoniex.PhoenixApp;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jdom.Element;
import phoniex.Core;
import phoniex.IO.Input;

/**
 *
 * @author Admin
 */
public class Jobs extends javax.swing.JFrame {

    /** Creates new form Jobs */
    Core core= PhoenixApp.getApplication().getCore();
    public Jobs() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        serverURLFeild.setText(core.getServer());
        if(core.getJobListDoc()!=null){
            DefaultListModel listModel= new DefaultListModel();
            List<Element> list = (List<Element>)Core.filter("//jobs", core.getJobListDoc());
            for(Element e:list)listModel.addElement(e.getText());
            jobList.setModel(listModel);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectJob = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jobList = new javax.swing.JList();
        jobListLable = new javax.swing.JLabel();
        serverURL = new javax.swing.JLabel();
        serverURLFeild = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectJob.setText("Select Job");
        selectJob.setName("selectJob"); // NOI18N
        selectJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectJobActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.setName("update"); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jobList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jobList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jobList.setName("jobList"); // NOI18N
        jScrollPane1.setViewportView(jobList);

        jobListLable.setText("Jobs:");
        jobListLable.setName("jobListLable"); // NOI18N

        serverURL.setText("Server URL:");
        serverURL.setName("serverURL"); // NOI18N

        serverURLFeild.setText("http://");
        serverURLFeild.setName("serverURLFeild"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectJob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(update))
                    .addComponent(jobListLable)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serverURL)
                        .addGap(18, 18, 18)
                        .addComponent(serverURLFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverURL)
                    .addComponent(serverURLFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jobListLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectJob)
                    .addComponent(update))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String url= serverURLFeild.getText();
        if(url.isEmpty()||url.equalsIgnoreCase("http://")) JOptionPane.showMessageDialog(null, "Please enter the server URL");
        else{
            core.setJobListDoc(Input.getJobs(url));
            core.setServer(url);
        }
        DefaultListModel listModel= new DefaultListModel();
        List<Element> list = (List<Element>)Core.filter("//job", core.getJobListDoc());
        for(Element e:list)listModel.addElement(e.getText());
        jobList.setModel(listModel);
    }//GEN-LAST:event_updateActionPerformed

    private void selectJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectJobActionPerformed
        core.setJobid((String)jobList.getSelectedValue());
        dispose();
    }//GEN-LAST:event_selectJobActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jobList;
    private javax.swing.JLabel jobListLable;
    private javax.swing.JButton selectJob;
    private javax.swing.JLabel serverURL;
    private javax.swing.JTextField serverURLFeild;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
