<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="xliff">

  <html>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<head>
            <style type="text/css">
                tr:nth-child(even) {background: #CCC}
                tr:nth-child(odd) {background: #FFF}
                tr:nth-child(1) {background: #201550}
                tr:nth-child(1) {color: #9f9a1f}
                
            </style>
            <title>Reuseage</title>
	</head>

	<body style="background:#fff; color:#000000; font-family:Verdana; font-size:20px" >
            <center>
                <xsl:for-each select="//file">
                   <p>This data has been generated by Xliff Phoenix <br/> The file processed was: </p>

                   <table style="margin:3px 50px 1px 25px; align:center; width:100px" border="0">
                       <xsl:value-of select="@original"/>
                   </table>
                   <br/>
                   <div style="overflow-x: auto; width: 90%;">
                    <table style="margin:3px 50px 1px 25px; align:center; width:95%" border="0">

                        <tr>
                            <th>Source Text</th>
                            <th>Alt-Target Text</th>
                            <th>Match %</th>
                            <th>Source Lang</th>
                            <th>Target Lang</th>
                           
                        </tr>

                        <xsl:for-each select="//body//trans-unit">
                            <tr>
                                <td width="25%"><xsl:value-of select="source"/></td>
                                <td width="25%"><xsl:value-of select="alt-trans/target"/></td>
                                <td width="5%"><xsl:value-of select="alt-trans/@match-quality"/></td>
                                <td width="5%"><xsl:value-of select="source/@xml:lang"/></td>
                                <td width="5%"><xsl:value-of select="alt-trans/target/@xml:lang"/></td>
                                
                            </tr>
                        </xsl:for-each>
                    </table>
                    </div>

                    <br/>
                    <br/>
                </xsl:for-each>


                <img  src="http://www.localisation.ie/Images/cngllogo.gif"/>

                <br/>

                <i>
                    <font size="1" style="color:#201550">
                   © 2010 UNIVERSITY OF LIMERICK.<br/>
                   All rights reserved.<br/>
                   This material may not be reproduced, displayed, modified or distributed without<br/>
                   the express prior written permission of the copyright holder.<br/>
                   This research is supported by the Science Foundation Ireland (Grant 07/CE/I1142) as part of the Centre for Next Generation Localisation (www.cngl.ie) at University of Limerick .<br/>
                    </font>
                </i>

            </center>
	</body>

  </html>

</xsl:template>
</xsl:stylesheet>