<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/">

  <html>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<head>
            <style type="text/css">
                tr:nth-child(even) {background: #CCC}
                tr:nth-child(odd) {background: #FFF}
                tr:nth-child(1) {background: #201550}
                tr:nth-child(1) {color: #9f9a1f}
                
            </style>
            <title>Reuseage</title>
	</head>

	<body style="background:#fff; color:#000000; font-family:Verdana; font-size:20px" >
            <center>
                <xsl:for-each select="//match-statistics">
                   <p>This data has been generated by XLIFF Phoenix </p>

                   <table style="margin:3px 50px 1px 25px; align:center; width:100px" border="0">
                       <xsl:value-of select="@original"/>
                   </table>
                   <br/>
                   <div style="overflow-x: auto; width: 90%;">
                    <table style="margin:3px 50px 1px 25px; align:center; width:95%" border="0">

                        <tr>
                            <th>Match Range</th>
                            <th>Segments</th>
                            <th>Percent of Document</th>
           
                        </tr>

                        <xsl:for-each select="//match-statistics//match-count">
                            <tr>
                                <td width="30%"><xsl:value-of select="@range"/></td>
                                <td width="30%"><xsl:value-of select="text()"/></td>
                                <td width="30%"><xsl:value-of select="@doc-percent"/></td>
                            </tr>
                        </xsl:for-each>
                    </table>
                    </div>

                    <br/>
                    <br/>
                </xsl:for-each>


                <img  src="http://www.localisation.ie/Images/cngllogo.gif"/>

                <br/>

                <i>
                    <font size="1" style="color:#201550">
                   ©2010 UNIVERSITY OF LIMERICK.<br/>
                   All rights reserved.<br/>
                   This material may not be reproduced, displayed, modified or distributed without<br/>
                   the express prior written permission of the copyright holder.<br/>
                   This research is supported by the Science Foundation Ireland (Grant 07/CE/I1142) as part of the Centre for Next Generation Localisation (www.cngl.ie) at University of Limerick .<br/>
                    </font>
                </i>

            </center>
	</body>

  </html>

</xsl:template>
</xsl:stylesheet>