/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvancedFilterView.java
 *
 * Created on 17-Jun-2010, 10:23:41
 */
package phoniex.GUI;

import com.centerkey.utils.BareBonesBrowserLaunch;
import java.awt.Color;
import javax.swing.JComboBox;
import phoniex.Core;

/**
 *
 * @author Admin
 */
public class AdvancedFilterView extends javax.swing.JFrame {

    /** Creates new form AdvancedFilterView */
    private FilterView filter;

    public AdvancedFilterView(FilterView filter) {
        this.filter = filter;
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setIconImage(Core.getLogo());
        setTitle("Advanced Filter");
    }

    public JComboBox getApprovedBox() {
        return approvedBox;
    }

    public JComboBox getLockedBox() {
        return lockedBox;
    }

    public String getCompanyNameFeild() {
        return companyNameFeild.getText().trim();
    }

    public String getContactNameField() {
        return contactNameField.getText().trim();
    }

    public String getEmailField() {
        return emailField.getText().trim();
    }

    public String getJobIdFeild() {
        return jobIdFeild.getText().trim();
    }

    public String getToolCompanyFeild() {
        return toolCompanyFeild.getText().trim();
    }

    public String getToolIdFeild() {
        return toolIdFeild.getText().trim();
    }
    public String getToolNameFeild() {
        return toolNameFeild.getText().trim();
    }
     public String getToolVersionFeild() {
        return toolVersionField.getText().trim();
    }

    public String getxliffVersion(){
        return ((String) versionBox.getSelectedItem()).trim();
    }

    public String getTransUnitStateField() {
        return ((String) transUnitStateBox.getSelectedItem()).trim();
    }

    public String getTransUnitStatusField() {
        return ((String) transUnitStatusBox.getSelectedItem()).trim();
    }

    public String getVersionField() {
        return ((String) versionBox.getSelectedItem()).trim();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLable = new javax.swing.JLabel();
        phasePanel = new javax.swing.JPanel();
        contactNameField = new javax.swing.JTextField();
        companyNameFeild = new javax.swing.JTextField();
        jobIdFeild = new javax.swing.JTextField();
        jobIdLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        companyNameLabel = new javax.swing.JLabel();
        ContactNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phaseLable = new javax.swing.JLabel();
        toolFilterLable = new javax.swing.JLabel();
        transUnitFilterLable = new javax.swing.JLabel();
        transUnitPanel = new javax.swing.JPanel();
        transUnitStateBox = new javax.swing.JComboBox();
        approvedLable = new javax.swing.JLabel();
        approvedBox = new javax.swing.JComboBox();
        tuStatusLable = new javax.swing.JLabel();
        transUnitStatusBox = new javax.swing.JComboBox();
        lockedBox = new javax.swing.JComboBox();
        lockedLable = new javax.swing.JLabel();
        transUnitStateLable = new javax.swing.JLabel();
        toolFilterPanel = new javax.swing.JPanel();
        toolCompanyLabel = new javax.swing.JLabel();
        toolIdLabel = new javax.swing.JLabel();
        toolIdFeild = new javax.swing.JTextField();
        toolCompanyFeild = new javax.swing.JTextField();
        toolNameLable = new javax.swing.JLabel();
        toolNameFeild = new javax.swing.JTextField();
        toolVersionLable = new javax.swing.JLabel();
        toolVersionField = new javax.swing.JTextField();
        xliffFilterPanel = new javax.swing.JPanel();
        versionLabel = new javax.swing.JLabel();
        versionBox = new javax.swing.JComboBox();
        xliffFilterLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        basicButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AdvancedFilterView.class);
        logoLable.setIcon(resourceMap.getIcon("logoLable.icon")); // NOI18N
        logoLable.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        logoLable.setName("logoLable"); // NOI18N

        phasePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, resourceMap.getColor("phasePanel.border.highlightColor"), resourceMap.getColor("phasePanel.border.shadowColor"))); // NOI18N
        phasePanel.setName("phasePanel"); // NOI18N

        contactNameField.setText(resourceMap.getString("contactNameField.text")); // NOI18N
        contactNameField.setToolTipText(resourceMap.getString("contactNameField.toolTipText")); // NOI18N
        contactNameField.setName("contactNameField"); // NOI18N

        companyNameFeild.setText(resourceMap.getString("companyNameFeild.text")); // NOI18N
        companyNameFeild.setToolTipText(resourceMap.getString("companyNameFeild.toolTipText")); // NOI18N
        companyNameFeild.setName("companyNameFeild"); // NOI18N

        jobIdFeild.setText(resourceMap.getString("jobIdFeild.text")); // NOI18N
        jobIdFeild.setToolTipText(resourceMap.getString("jobIdFeild.toolTipText")); // NOI18N
        jobIdFeild.setName("jobIdFeild"); // NOI18N

        jobIdLabel.setText(resourceMap.getString("jobIdLabel.text")); // NOI18N
        jobIdLabel.setName("jobIdLabel"); // NOI18N
        jobIdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobIdLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobIdLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jobIdLabelMouseExited(evt);
            }
        });

        emailField.setText(resourceMap.getString("emailField.text")); // NOI18N
        emailField.setToolTipText(resourceMap.getString("emailField.toolTipText")); // NOI18N
        emailField.setName("emailField"); // NOI18N

        companyNameLabel.setText(resourceMap.getString("companyNameLabel.text")); // NOI18N
        companyNameLabel.setName("companyNameLabel"); // NOI18N
        companyNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyNameLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                companyNameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                companyNameLabelMouseExited(evt);
            }
        });

        ContactNameLabel.setText(resourceMap.getString("ContactNameLabel.text")); // NOI18N
        ContactNameLabel.setName("ContactNameLabel"); // NOI18N
        ContactNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactNameLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactNameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactNameLabelMouseExited(evt);
            }
        });

        emailLabel.setText(resourceMap.getString("emailLabel.text")); // NOI18N
        emailLabel.setName("emailLabel"); // NOI18N
        emailLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout phasePanelLayout = new javax.swing.GroupLayout(phasePanel);
        phasePanel.setLayout(phasePanelLayout);
        phasePanelLayout.setHorizontalGroup(
            phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobIdLabel)
                    .addComponent(emailLabel)
                    .addComponent(ContactNameLabel)
                    .addComponent(companyNameLabel))
                .addGap(44, 44, 44)
                .addGroup(phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jobIdFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(companyNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        phasePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {companyNameFeild, contactNameField, emailField, jobIdFeild});

        phasePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ContactNameLabel, companyNameLabel, emailLabel, jobIdLabel});

        phasePanelLayout.setVerticalGroup(
            phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyNameLabel)
                    .addGroup(phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(phasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(phasePanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(contactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jobIdFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(companyNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(phasePanelLayout.createSequentialGroup()
                            .addComponent(ContactNameLabel)
                            .addGap(18, 18, 18)
                            .addComponent(emailLabel)
                            .addGap(18, 18, 18)
                            .addComponent(jobIdLabel))))
                .addContainerGap())
        );

        phasePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ContactNameLabel, companyNameFeild, companyNameLabel, contactNameField, emailField, emailLabel, jobIdFeild, jobIdLabel});

        phaseLable.setText(resourceMap.getString("phaseLable.text")); // NOI18N
        phaseLable.setName("phaseLable"); // NOI18N

        toolFilterLable.setText(resourceMap.getString("toolFilterLable.text")); // NOI18N
        toolFilterLable.setName("toolFilterLable"); // NOI18N

        transUnitFilterLable.setText(resourceMap.getString("transUnitFilterLable.text")); // NOI18N
        transUnitFilterLable.setName("transUnitFilterLable"); // NOI18N

        transUnitPanel.setBorder(phasePanel.getBorder());
        transUnitPanel.setName("transUnitPanel"); // NOI18N

        transUnitStateBox.setEditable(true);
        transUnitStateBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "exact-match", "fuzzy-match", "id-match", "leveraged-glossary", "leveraged-inherited", "leveraged-mt", "leveraged-repository", "leveraged-tm", "mt-suggestion", "rejected-grammar", "rejected-inaccurate", "rejected-length", "rejected-spelling", "tm-suggestion", "x-" }));
        transUnitStateBox.setToolTipText(resourceMap.getString("transUnitStateBox.toolTipText")); // NOI18N
        transUnitStateBox.setName("transUnitStateBox"); // NOI18N

        approvedLable.setText(resourceMap.getString("approvedLable.text")); // NOI18N
        approvedLable.setName("approvedLable"); // NOI18N
        approvedLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approvedLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                approvedLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                approvedLableMouseExited(evt);
            }
        });

        approvedBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "yes", "no" }));
        approvedBox.setToolTipText(resourceMap.getString("approvedBox.toolTipText")); // NOI18N
        approvedBox.setName("approvedBox"); // NOI18N

        tuStatusLable.setText(resourceMap.getString("tuStatusLable.text")); // NOI18N
        tuStatusLable.setName("tuStatusLable"); // NOI18N
        tuStatusLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuStatusLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tuStatusLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tuStatusLableMouseExited(evt);
            }
        });

        transUnitStatusBox.setEditable(true);
        transUnitStatusBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "final", "needs-adaptation", "needs-l10n", "needs-review-adaptation", "needs-review-l10n", "needs-review-translation", "needs-translation", "new", "signed-off", "translated", "x-" }));
        transUnitStatusBox.setToolTipText(resourceMap.getString("transUnitStatusBox.toolTipText")); // NOI18N
        transUnitStatusBox.setName("transUnitStatusBox"); // NOI18N

        lockedBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "yes", "no" }));
        lockedBox.setToolTipText(resourceMap.getString("lockedBox.toolTipText")); // NOI18N
        lockedBox.setName("lockedBox"); // NOI18N

        lockedLable.setText(resourceMap.getString("lockedLable.text")); // NOI18N
        lockedLable.setName("lockedLable"); // NOI18N
        lockedLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockedLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lockedLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lockedLableMouseExited(evt);
            }
        });

        transUnitStateLable.setText(resourceMap.getString("transUnitStateLable.text")); // NOI18N
        transUnitStateLable.setName("transUnitStateLable"); // NOI18N
        transUnitStateLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transUnitStateLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transUnitStateLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transUnitStateLableMouseExited(evt);
            }
        });

        javax.swing.GroupLayout transUnitPanelLayout = new javax.swing.GroupLayout(transUnitPanel);
        transUnitPanel.setLayout(transUnitPanelLayout);
        transUnitPanelLayout.setHorizontalGroup(
            transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transUnitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(approvedLable)
                    .addComponent(lockedLable)
                    .addComponent(tuStatusLable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transUnitStateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transUnitStateBox, 0, 146, Short.MAX_VALUE)
                    .addComponent(transUnitStatusBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(approvedBox, 0, 146, Short.MAX_VALUE)
                    .addComponent(lockedBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        transUnitPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {approvedBox, lockedBox, transUnitStateBox, transUnitStatusBox});

        transUnitPanelLayout.setVerticalGroup(
            transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transUnitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lockedLable)
                    .addComponent(lockedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(approvedLable)
                    .addGroup(transUnitPanelLayout.createSequentialGroup()
                        .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transUnitPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(tuStatusLable))
                            .addGroup(transUnitPanelLayout.createSequentialGroup()
                                .addComponent(approvedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transUnitStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(transUnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transUnitStateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transUnitStateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        transUnitPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {approvedBox, lockedBox, transUnitStateBox, transUnitStatusBox});

        toolFilterPanel.setBorder(phasePanel.getBorder());
        toolFilterPanel.setName("toolFilterPanel"); // NOI18N

        toolCompanyLabel.setText(resourceMap.getString("toolCompanyLabel.text")); // NOI18N
        toolCompanyLabel.setName("toolCompanyLabel"); // NOI18N
        toolCompanyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolCompanyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toolCompanyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolCompanyLabelMouseExited(evt);
            }
        });

        toolIdLabel.setText(resourceMap.getString("toolIdLabel.text")); // NOI18N
        toolIdLabel.setName("toolIdLabel"); // NOI18N
        toolIdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolIdLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toolIdLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolIdLabelMouseExited(evt);
            }
        });

        toolIdFeild.setText(resourceMap.getString("toolIdFeild.text")); // NOI18N
        toolIdFeild.setToolTipText(resourceMap.getString("toolIdFeild.toolTipText")); // NOI18N
        toolIdFeild.setName("toolIdFeild"); // NOI18N

        toolCompanyFeild.setText(resourceMap.getString("toolCompanyFeild.text")); // NOI18N
        toolCompanyFeild.setToolTipText(resourceMap.getString("toolCompanyFeild.toolTipText")); // NOI18N
        toolCompanyFeild.setName("toolCompanyFeild"); // NOI18N
        toolCompanyFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolCompanyFeildActionPerformed(evt);
            }
        });

        toolNameLable.setText(resourceMap.getString("toolNameLable.text")); // NOI18N
        toolNameLable.setName("toolNameLable"); // NOI18N
        toolNameLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolNameLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toolNameLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolNameLableMouseExited(evt);
            }
        });

        toolNameFeild.setText(resourceMap.getString("toolNameFeild.text")); // NOI18N
        toolNameFeild.setToolTipText(resourceMap.getString("toolNameFeild.toolTipText")); // NOI18N
        toolNameFeild.setName("toolNameFeild"); // NOI18N
        toolNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolNameFeildActionPerformed(evt);
            }
        });

        toolVersionLable.setText(resourceMap.getString("toolVersionLable.text")); // NOI18N
        toolVersionLable.setName("toolVersionLable"); // NOI18N
        toolVersionLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolVersionLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toolVersionLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toolVersionLableMouseExited(evt);
            }
        });

        toolVersionField.setText(resourceMap.getString("toolVersionField.text")); // NOI18N
        toolVersionField.setToolTipText(resourceMap.getString("toolVersionField.toolTipText")); // NOI18N
        toolVersionField.setName("toolVersionField"); // NOI18N
        toolVersionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolVersionFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolFilterPanelLayout = new javax.swing.GroupLayout(toolFilterPanel);
        toolFilterPanel.setLayout(toolFilterPanelLayout);
        toolFilterPanelLayout.setHorizontalGroup(
            toolFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolVersionLable, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolCompanyLabel)
                    .addComponent(toolIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toolNameLable))
                .addGap(18, 18, 18)
                .addGroup(toolFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toolCompanyFeild)
                    .addComponent(toolIdFeild)
                    .addComponent(toolNameFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(toolVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        toolFilterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {toolCompanyFeild, toolIdFeild, toolNameFeild, toolVersionField});

        toolFilterPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {toolCompanyLabel, toolIdLabel, toolNameLable, toolVersionLable});

        toolFilterPanelLayout.setVerticalGroup(
            toolFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(toolFilterPanelLayout.createSequentialGroup()
                        .addComponent(toolCompanyFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toolNameFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toolIdFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toolVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toolFilterPanelLayout.createSequentialGroup()
                        .addComponent(toolCompanyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(toolNameLable)
                        .addGap(18, 18, 18)
                        .addComponent(toolIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(toolVersionLable)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toolFilterPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {toolCompanyFeild, toolCompanyLabel, toolIdFeild, toolIdLabel, toolNameFeild, toolNameLable, toolVersionField, toolVersionLable});

        xliffFilterPanel.setBorder(phasePanel.getBorder());
        xliffFilterPanel.setName("xliffFilterPanel"); // NOI18N

        versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        versionLabel.setName("versionLabel"); // NOI18N
        versionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                versionLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versionLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                versionLabelMouseExited(evt);
            }
        });

        versionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "1.0", "1.1", "1.2" }));
        versionBox.setToolTipText(resourceMap.getString("versionBox.toolTipText")); // NOI18N
        versionBox.setName("versionBox"); // NOI18N

        javax.swing.GroupLayout xliffFilterPanelLayout = new javax.swing.GroupLayout(xliffFilterPanel);
        xliffFilterPanel.setLayout(xliffFilterPanelLayout);
        xliffFilterPanelLayout.setHorizontalGroup(
            xliffFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xliffFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(versionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        xliffFilterPanelLayout.setVerticalGroup(
            xliffFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xliffFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xliffFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        xliffFilterLable.setText(resourceMap.getString("xliffFilterLable.text")); // NOI18N
        xliffFilterLable.setName("xliffFilterLable"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toolFilterLable)
                            .addComponent(toolFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(logoLable)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(transUnitFilterLable)
                        .addComponent(xliffFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transUnitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(phaseLable)
                    .addComponent(xliffFilterLable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phaseLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(xliffFilterLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xliffFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toolFilterLable)
                    .addComponent(transUnitFilterLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(toolFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(transUnitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        basicButton.setText(resourceMap.getString("basicButton.text")); // NOI18N
        basicButton.setName("basicButton"); // NOI18N
        basicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(basicButton)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(basicButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicButtonActionPerformed
        filter.setAdvanced(false);
        dispose();
    }

    {
}//GEN-LAST:event_basicButtonActionPerformed

    private void toolNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolNameFeildActionPerformed

    private void toolVersionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolVersionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolVersionFieldActionPerformed

    private void toolCompanyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolCompanyLabelMouseClicked
       BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#tool-company");
    }//GEN-LAST:event_toolCompanyLabelMouseClicked

    private void toolCompanyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolCompanyLabelMouseEntered
        toolCompanyLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_toolCompanyLabelMouseEntered

    private void toolCompanyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolCompanyLabelMouseExited
        toolCompanyLabel.setForeground(Color.black);
    }//GEN-LAST:event_toolCompanyLabelMouseExited

    private void toolNameLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolNameLableMouseClicked
       BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#tool-name");
    }//GEN-LAST:event_toolNameLableMouseClicked

    private void toolNameLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolNameLableMouseEntered
        toolNameLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_toolNameLableMouseEntered

    private void toolNameLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolNameLableMouseExited
        toolNameLable.setForeground(Color.black);
    }//GEN-LAST:event_toolNameLableMouseExited

    private void toolIdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolIdLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#tool-id");
    }//GEN-LAST:event_toolIdLabelMouseClicked

    private void toolIdLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolIdLabelMouseEntered
        toolIdLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_toolIdLabelMouseEntered

    private void toolIdLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolIdLabelMouseExited
        toolIdLabel.setForeground(Color.black);
    }//GEN-LAST:event_toolIdLabelMouseExited

    private void toolVersionLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolVersionLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#tool-version");
    }//GEN-LAST:event_toolVersionLableMouseClicked

    private void toolVersionLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolVersionLableMouseEntered
       toolVersionLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_toolVersionLableMouseEntered

    private void toolVersionLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolVersionLableMouseExited
        toolVersionLable.setForeground(Color.black);
    }//GEN-LAST:event_toolVersionLableMouseExited

    private void companyNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#company-name");
    }//GEN-LAST:event_companyNameLabelMouseClicked

    private void companyNameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameLabelMouseEntered
        companyNameLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_companyNameLabelMouseEntered

    private void companyNameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameLabelMouseExited
       companyNameLabel.setForeground(Color.black);
    }//GEN-LAST:event_companyNameLabelMouseExited

    private void ContactNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactNameLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#contact-name");
    }//GEN-LAST:event_ContactNameLabelMouseClicked

    private void ContactNameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactNameLabelMouseEntered
        ContactNameLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_ContactNameLabelMouseEntered

    private void ContactNameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactNameLabelMouseExited
        ContactNameLabel.setForeground(Color.black);
    }//GEN-LAST:event_ContactNameLabelMouseExited

    private void emailLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#contact-email");
    }//GEN-LAST:event_emailLabelMouseClicked

    private void emailLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLabelMouseEntered
        emailLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_emailLabelMouseEntered

    private void emailLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLabelMouseExited
        emailLabel.setForeground(Color.black);
    }//GEN-LAST:event_emailLabelMouseExited

    private void jobIdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobIdLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#job-id");
    }//GEN-LAST:event_jobIdLabelMouseClicked

    private void jobIdLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobIdLabelMouseEntered
        jobIdLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_jobIdLabelMouseEntered

    private void jobIdLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobIdLabelMouseExited
        jobIdLabel.setForeground(Color.black);
    }//GEN-LAST:event_jobIdLabelMouseExited

    private void versionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#version");
    }//GEN-LAST:event_versionLabelMouseClicked

    private void versionLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionLabelMouseEntered
        versionLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_versionLabelMouseEntered

    private void versionLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionLabelMouseExited
        versionLabel.setForeground(Color.black);
    }//GEN-LAST:event_versionLabelMouseExited

    private void lockedLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockedLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#translate");
    }//GEN-LAST:event_lockedLableMouseClicked

    private void lockedLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockedLableMouseEntered
        lockedLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_lockedLableMouseEntered

    private void lockedLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockedLableMouseExited
        lockedLable.setForeground(Color.black);
    }//GEN-LAST:event_lockedLableMouseExited

    private void approvedLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvedLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#approved");
    }//GEN-LAST:event_approvedLableMouseClicked

    private void approvedLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvedLableMouseEntered
        approvedLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_approvedLableMouseEntered

    private void approvedLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvedLableMouseExited
        approvedLable.setForeground(Color.black);
    }//GEN-LAST:event_approvedLableMouseExited

    private void tuStatusLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuStatusLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state-qualifier");
    }//GEN-LAST:event_tuStatusLableMouseClicked

    private void tuStatusLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuStatusLableMouseEntered
        tuStatusLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_tuStatusLableMouseEntered

    private void tuStatusLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tuStatusLableMouseExited
        tuStatusLable.setForeground(Color.black);
    }//GEN-LAST:event_tuStatusLableMouseExited

    private void transUnitStateLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transUnitStateLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state");
    }//GEN-LAST:event_transUnitStateLableMouseClicked

    private void transUnitStateLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transUnitStateLableMouseEntered
        transUnitStateLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_transUnitStateLableMouseEntered

    private void transUnitStateLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transUnitStateLableMouseExited
        transUnitStateLable.setForeground(Color.black);
    }//GEN-LAST:event_transUnitStateLableMouseExited

    private void toolCompanyFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolCompanyFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolCompanyFeildActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContactNameLabel;
    private javax.swing.JComboBox approvedBox;
    private javax.swing.JLabel approvedLable;
    private javax.swing.JButton basicButton;
    private javax.swing.JTextField companyNameFeild;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JTextField contactNameField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jobIdFeild;
    private javax.swing.JLabel jobIdLabel;
    private javax.swing.JComboBox lockedBox;
    private javax.swing.JLabel lockedLable;
    private javax.swing.JLabel logoLable;
    private javax.swing.JLabel phaseLable;
    private javax.swing.JPanel phasePanel;
    private javax.swing.JTextField toolCompanyFeild;
    private javax.swing.JLabel toolCompanyLabel;
    private javax.swing.JLabel toolFilterLable;
    private javax.swing.JPanel toolFilterPanel;
    private javax.swing.JTextField toolIdFeild;
    private javax.swing.JLabel toolIdLabel;
    private javax.swing.JTextField toolNameFeild;
    private javax.swing.JLabel toolNameLable;
    private javax.swing.JTextField toolVersionField;
    private javax.swing.JLabel toolVersionLable;
    private javax.swing.JLabel transUnitFilterLable;
    private javax.swing.JPanel transUnitPanel;
    private javax.swing.JComboBox transUnitStateBox;
    private javax.swing.JLabel transUnitStateLable;
    private javax.swing.JComboBox transUnitStatusBox;
    private javax.swing.JLabel tuStatusLable;
    private javax.swing.JComboBox versionBox;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel xliffFilterLable;
    private javax.swing.JPanel xliffFilterPanel;
    // End of variables declaration//GEN-END:variables
}
