/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FilterView.java
 *
 * Created on 14-Jun-2010, 16:09:22
 */

package phoniex.GUI;

import com.centerkey.utils.BareBonesBrowserLaunch;
import java.awt.Color;
import phoniex.IO.Output;
import javax.swing.JEditorPane;
import org.jdom.Document;
import phoniex.Core;
import phoniex.Filter;
import phoniex.IFilter;



/**
 *
 * @author sean
 */
public class FilterView  extends javax.swing.JFrame{
    private Core core;
    private Document doc;
    private Document repos;
    private JEditorPane textTab;
    private boolean advanced;
    private AdvancedFilterView aFilter;
    boolean finished=false;
    private IFilter filter=null;

    /** Creates new form FilterView */
    private FilterView() {
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setIconImage(Core.getLogo());
        setTitle("General Filter");
    }
    public FilterView(Core c) {
          this();
          this.core = c;
          this.repos=core.getRepos();
          filter = Filter.newFilter(repos);
          Output.display(core.getRepos(), searchView);
    }
    public FilterView(Core c, JEditorPane textArea) {
          this(c);
          this.textTab = textArea;
    }

    @Override
    public void dispose(){
     if(aFilter!=null){ 
         aFilter.dispose();
         aFilter=null;
     }
     super.dispose();
    }

    public void setAdvanced(boolean advanced) {
        this.advanced = advanced;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchView = new WTextPane();
        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        advancedButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        sourceLanguageLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        startdateField = new javax.swing.JTextField();
        sourceLanguageField = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        formatLable = new javax.swing.JLabel();
        targetLanguageLabel = new javax.swing.JLabel();
        targetLanguageField = new javax.swing.JTextField();
        fileNameLable = new javax.swing.JLabel();
        formatBox = new javax.swing.JComboBox();
        fieldLable = new javax.swing.JLabel();
        fileField = new javax.swing.JTextField();
        endDateLabel = new javax.swing.JLabel();
        endDateFeild = new javax.swing.JTextField();
        domainField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        searchView.setName("searchView"); // NOI18N
        jScrollPane1.setViewportView(searchView);

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(FilterView.class);
        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        cancleButton.setText(resourceMap.getString("cancleButton.text")); // NOI18N
        cancleButton.setName("cancleButton"); // NOI18N
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancleButton);

        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(applyButton);

        advancedButton.setText(resourceMap.getString("advancedButton.text")); // NOI18N
        advancedButton.setName("advancedButton"); // NOI18N
        advancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedButtonActionPerformed(evt);
            }
        });
        jPanel1.add(advancedButton);

        jPanel2.setName("jPanel2"); // NOI18N

        sourceLanguageLabel.setLabelFor(sourceLanguageField);
        sourceLanguageLabel.setText(resourceMap.getString("sourceLanguageLabel.text")); // NOI18N
        sourceLanguageLabel.setName("sourceLanguageLabel"); // NOI18N
        sourceLanguageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourceLanguageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sourceLanguageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sourceLanguageLabelMouseExited(evt);
            }
        });

        startDateLabel.setLabelFor(startdateField);
        startDateLabel.setText(resourceMap.getString("startDateLabel.text")); // NOI18N
        startDateLabel.setName("startDateLabel"); // NOI18N
        startDateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startDateLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startDateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startDateLabelMouseExited(evt);
            }
        });

        startdateField.setText(resourceMap.getString("startdateField.text")); // NOI18N
        startdateField.setToolTipText(resourceMap.getString("startdateField.toolTipText")); // NOI18N
        startdateField.setName("startdateField"); // NOI18N
        startdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startdateFieldActionPerformed(evt);
            }
        });

        sourceLanguageField.setText(resourceMap.getString("sourceLanguageField.text")); // NOI18N
        sourceLanguageField.setToolTipText(resourceMap.getString("sourceLanguageField.toolTipText")); // NOI18N
        sourceLanguageField.setMargin(new java.awt.Insets(2, 3, 3, 2));
        sourceLanguageField.setName("sourceLanguageField"); // NOI18N

        image.setIcon(resourceMap.getIcon("image.icon")); // NOI18N
        image.setName("image"); // NOI18N

        formatLable.setText(resourceMap.getString("formatLable.text")); // NOI18N
        formatLable.setName("formatLable"); // NOI18N
        formatLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formatLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formatLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formatLableMouseExited(evt);
            }
        });

        targetLanguageLabel.setText(resourceMap.getString("targetLanguageLabel.text")); // NOI18N
        targetLanguageLabel.setName("targetLanguageLabel"); // NOI18N
        targetLanguageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                targetLanguageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                targetLanguageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                targetLanguageLabelMouseExited(evt);
            }
        });

        targetLanguageField.setText(resourceMap.getString("targetLanguageField.text")); // NOI18N
        targetLanguageField.setToolTipText(resourceMap.getString("targetLanguageField.toolTipText")); // NOI18N
        targetLanguageField.setName("targetLanguageField"); // NOI18N
        targetLanguageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetLanguageFieldActionPerformed(evt);
            }
        });

        fileNameLable.setText(resourceMap.getString("fileNameLable.text")); // NOI18N
        fileNameLable.setName("fileNameLable"); // NOI18N
        fileNameLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileNameLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileNameLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fileNameLableMouseExited(evt);
            }
        });

        formatBox.setEditable(true);
        formatBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "any", "asp", "cdf", "cfm", "cpp", "csharp", "cstring", "csv", "documentfooter", "documentheader", "form", "html", "htmlbody", "ini", "interleaf", "javaclass", "javapropertyresourcebundle", "javalistresourcebundle", "javascript", "jscript", "layout", "lisp", "margin", "menufile", "messagefile", "mif", "mimetype", "mo", "msglib", "pagefooter", "pageheader", "parameters", "pascal", "php", "plaintext", "po", "report", "resources", "resx", "rtf", "sgml", "sgmldtd", "svg", "vbscript", "warning", "winres", "xhtml", "xml", "xmldtd", "xsl", "xul", "x-" }));
        formatBox.setToolTipText(resourceMap.getString("formatBox.toolTipText")); // NOI18N
        formatBox.setName("formatBox"); // NOI18N
        formatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatBoxActionPerformed(evt);
            }
        });

        fieldLable.setText(resourceMap.getString("fieldLable.text")); // NOI18N
        fieldLable.setName("fieldLable"); // NOI18N
        fieldLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fieldLableMouseExited(evt);
            }
        });

        fileField.setText(resourceMap.getString("fileField.text")); // NOI18N
        fileField.setToolTipText(resourceMap.getString("fileField.toolTipText")); // NOI18N
        fileField.setName("fileField"); // NOI18N

        endDateLabel.setLabelFor(startdateField);
        endDateLabel.setText(resourceMap.getString("endDateLabel.text")); // NOI18N
        endDateLabel.setName("endDateLabel"); // NOI18N
        endDateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endDateLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                endDateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                endDateLabelMouseExited(evt);
            }
        });

        endDateFeild.setText(resourceMap.getString("endDateFeild.text")); // NOI18N
        endDateFeild.setToolTipText(resourceMap.getString("endDateFeild.toolTipText")); // NOI18N
        endDateFeild.setMargin(new java.awt.Insets(2, 3, 3, 2));
        endDateFeild.setName("endDateFeild"); // NOI18N

        domainField.setText(resourceMap.getString("domainField.text")); // NOI18N
        domainField.setToolTipText(resourceMap.getString("domainField.toolTipText")); // NOI18N
        domainField.setName("domainField"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(image, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetLanguageLabel)
                            .addComponent(sourceLanguageLabel)
                            .addComponent(fileNameLable)
                            .addComponent(formatLable)
                            .addComponent(startDateLabel)
                            .addComponent(endDateLabel)
                            .addComponent(fieldLable))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fileField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(domainField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateFeild)
                            .addComponent(startdateField)
                            .addComponent(sourceLanguageField)
                            .addComponent(formatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(targetLanguageField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {domainField, endDateFeild, fileField, formatBox, sourceLanguageField, startdateField, targetLanguageField});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {endDateLabel, fieldLable, fileNameLable, formatLable, sourceLanguageLabel, startDateLabel, targetLanguageLabel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fileNameLable)
                        .addGap(18, 18, 18)
                        .addComponent(fieldLable)
                        .addGap(15, 15, 15)
                        .addComponent(targetLanguageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sourceLanguageLabel)
                        .addGap(18, 18, 18)
                        .addComponent(formatLable)
                        .addGap(18, 18, 18)
                        .addComponent(startDateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(endDateLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(domainField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(targetLanguageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sourceLanguageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(formatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(startdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(endDateFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {domainField, endDateFeild, endDateLabel, fieldLable, fileField, fileNameLable, formatBox, formatLable, sourceLanguageField, sourceLanguageLabel, startDateLabel, startdateField, targetLanguageField, targetLanguageLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
     this.dispose();
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        updateFilter();
        doc=filter.refine();
        Output.display(doc, searchView);
    }

    protected void updateFilter(){
        Filter cFilter = (Filter)filter;
        cFilter.setStartDate(startdateField.getText());
        cFilter.setEndDate(endDateFeild.getText());

        cFilter.setFile(fileField.getText());
        cFilter.setFormat((String)formatBox.getSelectedItem());
        cFilter.setSlang(sourceLanguageField.getText());
        cFilter.setTlang(targetLanguageField.getText());
        cFilter.setFeild(domainField.getText());
        if(advanced){cFilter.setApproved((String)aFilter.getApprovedBox().getSelectedItem());
        cFilter.setTool(aFilter.getToolNameFeild());
        cFilter.setCompanyName(aFilter.getCompanyNameFeild());
        cFilter.setEmail(aFilter.getEmailField());
        cFilter.setContactName(aFilter.getContactNameField());
        cFilter.setJobId(aFilter.getJobIdFeild());
        cFilter.setToolCompany(aFilter.getToolCompanyFeild());
        cFilter.setToolId(aFilter.getToolIdFeild());
        cFilter.setToolVersion(aFilter.getToolVersionFeild());
        cFilter.setTransUnitState(aFilter.getTransUnitStateField());
        cFilter.setTransUnitStatus(aFilter.getTransUnitStatusField());
        cFilter.setTranslate((String)aFilter.getLockedBox().getSelectedItem());
        cFilter.setVersion(aFilter.getVersionField());
        }
    }

    {
    }//GEN-LAST:event_applyButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      updateFilter();
      if(doc==null) doc=filter.refine();
      core.setFilteredRepos(doc);
      if(textTab!=null)Output.display(doc, textTab);
      this.dispose();
      finished=true;
    
    }//GEN-LAST:event_okButtonActionPerformed

    private void advancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedButtonActionPerformed
        advanced = true;
        aFilter = new AdvancedFilterView(this);

    }//GEN-LAST:event_advancedButtonActionPerformed

    private void targetLanguageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetLanguageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetLanguageFieldActionPerformed

    private void fileNameLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#original");
    }//GEN-LAST:event_fileNameLableMouseClicked

    private void fieldLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#category");
    }//GEN-LAST:event_fieldLableMouseClicked

    private void targetLanguageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetLanguageLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#target-language");
    }//GEN-LAST:event_targetLanguageLabelMouseClicked

    private void sourceLanguageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceLanguageLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#source-language");
    }//GEN-LAST:event_sourceLanguageLabelMouseClicked

    private void formatLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatLableMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#datatype");
    }//GEN-LAST:event_formatLableMouseClicked

    private void startDateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startDateLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#date");
    }//GEN-LAST:event_startDateLabelMouseClicked

    private void endDateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateLabelMouseClicked
        BareBonesBrowserLaunch.openURL("http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#date");
    }//GEN-LAST:event_endDateLabelMouseClicked

    private void fileNameLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameLableMouseEntered
      fileNameLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_fileNameLableMouseEntered

    private void fileNameLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileNameLableMouseExited
       fileNameLable.setForeground(Color.black);
    }//GEN-LAST:event_fileNameLableMouseExited

    private void fieldLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldLableMouseEntered
        fieldLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_fieldLableMouseEntered

    private void fieldLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldLableMouseExited
        fieldLable.setForeground(Color.black);
    }//GEN-LAST:event_fieldLableMouseExited

    private void targetLanguageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetLanguageLabelMouseEntered
       targetLanguageLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_targetLanguageLabelMouseEntered

    private void targetLanguageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetLanguageLabelMouseExited
        targetLanguageLabel.setForeground(Color.black);
    }//GEN-LAST:event_targetLanguageLabelMouseExited

    private void sourceLanguageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceLanguageLabelMouseEntered
        sourceLanguageLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_sourceLanguageLabelMouseEntered

    private void sourceLanguageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourceLanguageLabelMouseExited
        sourceLanguageLabel.setForeground(Color.black);
    }//GEN-LAST:event_sourceLanguageLabelMouseExited

    private void formatLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatLableMouseEntered
        formatLable.setForeground(Color.BLUE);
    }//GEN-LAST:event_formatLableMouseEntered

    private void formatLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatLableMouseExited
       formatLable.setForeground(Color.black);
    }//GEN-LAST:event_formatLableMouseExited

    private void startDateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startDateLabelMouseEntered
        startDateLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_startDateLabelMouseEntered

    private void startDateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startDateLabelMouseExited
        startDateLabel.setForeground(Color.black);
    }//GEN-LAST:event_startDateLabelMouseExited

    private void endDateLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateLabelMouseEntered
        endDateLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_endDateLabelMouseEntered

    private void endDateLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateLabelMouseExited
        endDateLabel.setForeground(Color.black);
    }//GEN-LAST:event_endDateLabelMouseExited

    private void formatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatBoxActionPerformed

    private void startdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startdateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startdateFieldActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advancedButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton cancleButton;
    private javax.swing.JTextField domainField;
    private javax.swing.JTextField endDateFeild;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel fieldLable;
    private javax.swing.JTextField fileField;
    private javax.swing.JLabel fileNameLable;
    private javax.swing.JComboBox formatBox;
    private javax.swing.JLabel formatLable;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextPane searchView;
    private javax.swing.JTextField sourceLanguageField;
    private javax.swing.JLabel sourceLanguageLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startdateField;
    private javax.swing.JTextField targetLanguageField;
    private javax.swing.JLabel targetLanguageLabel;
    // End of variables declaration//GEN-END:variables

}
